### ISSUE TITLE
Websocket连接在大量传输数据时会断开

### ISSUE THREAD

**Issue by lf1029698952** [du2016/web-terminal-in-go#2]
你好，我在使用k8s-webshell时，进入容器后，发现Websocket连接在大量传输数据时会断开连接，比如cat一个较大的文件，console报错如下：
![image](https://user-images.githubusercontent.com/11751263/50463197-2e35dd00-09c5-11e9-84df-984bf628a03c.png)
```
failed: Could not decode a text frame as UTF-8.
```
在查阅资料后，初步分析为websocket协议的数据帧大小默认为128字节，在进行大数据传输时，需要进行分片发送。
参考链接：[https://blog.csdn.net/man_sion/article/details/77334822](https://blog.csdn.net/man_sion/article/details/77334822)

**Comment by du2016** [comment]
修改为sockjs解决

**Comment by lf1029698952** [comment]
非常棒，sockjs自带心跳连接机制，使用起来体验好很多。
