### ISSUE TITLE
k8s terminal 连接启动的/bin/sh， 在连接后不会断开，依然存在，这每连接一次就会多一个

### ISSUE THREAD

**Issue by yueyongyue** [du2016/web-terminal-in-go#3]
142 root       0:00 /bin/sh
  156 root       0:00 /bin/sh
  165 root       0:00 /bin/sh
  201 root       0:00 /bin/sh
  214 root       0:00 /bin/sh
  233 root       0:00 /bin/sh
  255 root       0:00 /bin/sh
  274 root       0:00 /bin/sh
  286 root       0:00 /bin/sh
  298 root       0:00 ps

**Comment by du2016** [comment]
暂时没有好的解决办法，可以写个任务，定期清理

**Comment by lf1029698952** [comment]
@yueyongyue 你可以在每次退出容器时不直接关闭浏览器，先使用exit命令退出，不过这个并不影响，官方的kube-dashboard依然存在这个问题

**Comment by yueyongyue** [comment]
嗯嗯，发现了官方的也是这样，多谢各位
