### ISSUE TITLE
inappropriate ioctl for device

### ISSUE THREAD

**Issue by domechn** [du2016/web-terminal-in-go#7]
hi，您好，我在docker container中运行到[inFd, _ := term.GetFdInfo(t.conn)](https://github.com/du2016/web-terminal-in-go/blob/master/k8s-webshell/controllers/terminalws.go#L122)的时候会报
**inappropriate ioctl for device**
的错误，但是在本机上运行却没有这错误。而且我删除了和term相关的代码后，程序也能正常运行。

我想请问这段代码具体的作用是什么？

**Comment by du2016** [comment]
没作用  想实现命令行交互的话有作用
